db: bmr
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro,log4j2
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://8.133.180.154:3306/${db}?characterEncoding=UTF-8&useSSL=false
    username: root
    password: ZhiJian_20201222


